name: yolov4-triton
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.4.13=h06a4308_1
  - certifi=2020.12.5=py37h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.1.1=py37h06a4308_0
  - python=3.7.10=hdb3f193_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - gevent==21.1.2
    - geventhttpclient==1.4.4
    - greenlet==1.1.0
    - grpcio==1.38.0
    - numpy==1.20.3
    - opencv-python==4.5.2.52
    - protobuf==3.17.1
    - python-rapidjson==1.0
    - six==1.16.0
    - tritonclient==2.8.0
    - zope-event==4.5.0
    - zope-interface==5.4.0
